global using FourLines.Domain.Interfaces;
global using FourLines.Domain.Models;
global using FourLines.Infrastructure.Contexts;
global using FourLines.Infrastructure.Repositories;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
